[build]
  publish = "public"
  command = "node ./scripts/build-manifests.mjs.js"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/datas/*"
  to   = "/.netlify/functions/datas/:splat"
  status = 200

[[redirects]]
  from = "/manifest/*"
  to   = "/.netlify/functions/manifest/:splat"
  status = 200
